spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.4:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  session:
    store-type: none
security:
  basic:
    enabled: false